import { SvgProps } from 'react-native-svg'
import { FC } from 'react'

export interface IconProps extends SvgProps {
  size?: number
  color?: string
}

export declare const Add: FC<IconProps>
export declare const Apple: FC<IconProps>
export declare const ArrowBottom: FC<IconProps>
export declare const ArrowRight: FC<IconProps>
export declare const ArrowTop: FC<IconProps>
export declare const Bag2: FC<IconProps>
export declare const Bolt: FC<IconProps>
export declare const BudlyLogo: FC<IconProps>
export declare const Checklist: FC<IconProps>
export declare const Claimed: FC<IconProps>
export declare const ClaimLocked: FC<IconProps>
export declare const ClaimUnlocked: FC<IconProps>
export declare const ConditionsIcon: FC<IconProps>
export declare const ConfidentialyIcon: FC<IconProps>
export declare const Darkmode: FC<IconProps>
export declare const Delivery: FC<IconProps>
export declare const Desktop: FC<IconProps>
export declare const Diamond: FC<IconProps>
export declare const Diamond2: FC<IconProps>
export declare const Discovery: FC<IconProps>
export declare const DropWaving: FC<IconProps>
export declare const Edit: FC<IconProps>
export declare const Eye: FC<IconProps>
export declare const EyesPswClosed: FC<IconProps>
export declare const EyesPswOpen: FC<IconProps>
export declare const Facebook: FC<IconProps>
export declare const Faq: FC<IconProps>
export declare const FeatureSearch: FC<IconProps>
export declare const FilledHeart: FC<IconProps>
export declare const FingerPrint: FC<IconProps>
export declare const Fire: FC<IconProps>
export declare const FlagEn: FC<IconProps>
export declare const FlagEs: FC<IconProps>
export declare const FlagFr: FC<IconProps>
export declare const Game: FC<IconProps>
export declare const GiftHome: FC<IconProps>
export declare const GlobalMovement: FC<IconProps>
export declare const Google: FC<IconProps>
export declare const GoogleMyBusiness: FC<IconProps>
export declare const HeartLinear: FC<IconProps>
export declare const Light: FC<IconProps>
export declare const LineAdd: FC<IconProps>
export declare const LineArrow: FC<IconProps>
export declare const LineArrowBottom: FC<IconProps>
export declare const LineArrowLeft: FC<IconProps>
export declare const LineArrowRight: FC<IconProps>
export declare const LineArrowSwap: FC<IconProps>
export declare const LineArrowTop: FC<IconProps>
export declare const LineArrowVertical: FC<IconProps>
export declare const LineAward: FC<IconProps>
export declare const LineAward2: FC<IconProps>
export declare const LineBag: FC<IconProps>
export declare const LineBubble: FC<IconProps>
export declare const LineBudReal: FC<IconProps>
export declare const LineBudRealOff: FC<IconProps>
export declare const LineBuilding: FC<IconProps>
export declare const LineBusinessCard: FC<IconProps>
export declare const LineCalendar: FC<IconProps>
export declare const LineCamera: FC<IconProps>
export declare const LineCamera2: FC<IconProps>
export declare const LineCard: FC<IconProps>
export declare const LineCheck: FC<IconProps>
export declare const LineCheck2: FC<IconProps>
export declare const LineChest: FC<IconProps>
export declare const LineClock: FC<IconProps>
export declare const LineClose: FC<IconProps>
export declare const LineCopy: FC<IconProps>
export declare const LineCross: FC<IconProps>
export declare const LineDiamond: FC<IconProps>
export declare const LineDiscovery: FC<IconProps>
export declare const LineDownload: FC<IconProps>
export declare const LineDrag: FC<IconProps>
export declare const LineDragVertical: FC<IconProps>
export declare const LineEdit: FC<IconProps>
export declare const LineEdit2: FC<IconProps>
export declare const LineEdit3: FC<IconProps>
export declare const LineExit: FC<IconProps>
export declare const LineExit2: FC<IconProps>
export declare const LineExport: FC<IconProps>
export declare const LineFaceId: FC<IconProps>
export declare const LineFaq: FC<IconProps>
export declare const LineFilter: FC<IconProps>
export declare const LineFlashOff: FC<IconProps>
export declare const LineFlashOn: FC<IconProps>
export declare const LineFocus: FC<IconProps>
export declare const LineFocusGreen: FC<IconProps>
export declare const LineFocusGrey: FC<IconProps>
export declare const LineGallery: FC<IconProps>
export declare const LineGallery1: FC<IconProps>
export declare const LineGift: FC<IconProps>
export declare const LineGlasses: FC<IconProps>
export declare const LineHand: FC<IconProps>
export declare const LineHappy: FC<IconProps>
export declare const LineHeart: FC<IconProps>
export declare const LineHome: FC<IconProps>
export declare const LineIcon: FC<IconProps>
export declare const LineIncrease: FC<IconProps>
export declare const LineIncreaseLinear: FC<IconProps>
export declare const LineInfo: FC<IconProps>
export declare const LineLanguage: FC<IconProps>
export declare const LineLink: FC<IconProps>
export declare const LineLocation: FC<IconProps>
export declare const LineLock: FC<IconProps>
export declare const LineMall: FC<IconProps>
export declare const LineMarking: FC<IconProps>
export declare const LineMenu: FC<IconProps>
export declare const LineMenu2: FC<IconProps>
export declare const LineMerge: FC<IconProps>
export declare const LineMessage: FC<IconProps>
export declare const LineMessage3: FC<IconProps>
export declare const LineMessage3Primary: FC<IconProps>
export declare const LineMessage4: FC<IconProps>
export declare const LineMessage5: FC<IconProps>
export declare const LineMic: FC<IconProps>
export declare const LineMobile: FC<IconProps>
export declare const LineMoon: FC<IconProps>
export declare const LineMore: FC<IconProps>
export declare const LineMoreVertical: FC<IconProps>
export declare const LineMultipleBubble: FC<IconProps>
export declare const LineNewVersion: FC<IconProps>
export declare const LineNft: FC<IconProps>
export declare const LineNotification: FC<IconProps>
export declare const LineNoWifi: FC<IconProps>
export declare const LineParagraph: FC<IconProps>
export declare const LinePassword: FC<IconProps>
export declare const LinePause: FC<IconProps>
export declare const LinePhone: FC<IconProps>
export declare const LinePlane: FC<IconProps>
export declare const LinePlay: FC<IconProps>
export declare const LinePlay2: FC<IconProps>
export declare const LinePlus: FC<IconProps>
export declare const LinePreference: FC<IconProps>
export declare const LineQuestion: FC<IconProps>
export declare const LineQuestionPrimary: FC<IconProps>
export declare const LineReactBubble: FC<IconProps>
export declare const LineRefresh: FC<IconProps>
export declare const LineReport: FC<IconProps>
export declare const LineRow: FC<IconProps>
export declare const LineSaved: FC<IconProps>
export declare const LineScan: FC<IconProps>
export declare const LineScan2: FC<IconProps>
export declare const LineSearch: FC<IconProps>
export declare const LineSeed: FC<IconProps>
export declare const LineSend: FC<IconProps>
export declare const LineSetting: FC<IconProps>
export declare const LineSetting2: FC<IconProps>
export declare const LineSettingGame: FC<IconProps>
export declare const LineShakePhone: FC<IconProps>
export declare const LineShieldVulnerable: FC<IconProps>
export declare const LineShoppingBasket: FC<IconProps>
export declare const LineShoppingCart: FC<IconProps>
export declare const LineSliderVertical: FC<IconProps>
export declare const LineStar: FC<IconProps>
export declare const LinestarIa: FC<IconProps>
export declare const LineStarShield: FC<IconProps>
export declare const LineStatus: FC<IconProps>
export declare const LineSteps: FC<IconProps>
export declare const LineSun: FC<IconProps>
export declare const LineTag: FC<IconProps>
export declare const LineTarget: FC<IconProps>
export declare const LineThunder: FC<IconProps>
export declare const LineThunder3D: FC<IconProps>
export declare const LineTick: FC<IconProps>
export declare const LineTrash: FC<IconProps>
export declare const LineTravel: FC<IconProps>
export declare const LineTrophy: FC<IconProps>
export declare const LineTurnOff: FC<IconProps>
export declare const LineTwoUsers: FC<IconProps>
export declare const LineUnlock: FC<IconProps>
export declare const LineUser: FC<IconProps>
export declare const LineUserPlus: FC<IconProps>
export declare const LineVolume: FC<IconProps>
export declare const LineVolumeSlash: FC<IconProps>
export declare const LineWallet: FC<IconProps>
export declare const LineWarning: FC<IconProps>
export declare const LineWater: FC<IconProps>
export declare const LineWave: FC<IconProps>
export declare const LineWifi: FC<IconProps>
export declare const LineWork: FC<IconProps>
export declare const LineZoomGreen: FC<IconProps>
export declare const Loading: FC<IconProps>
export declare const Mobile: FC<IconProps>
export declare const Music: FC<IconProps>
export declare const Nfc: FC<IconProps>
export declare const NfcIcon: FC<IconProps>
export declare const NotClaimed: FC<IconProps>
export declare const PlantedDrop: FC<IconProps>
export declare const PlantedLocation: FC<IconProps>
export declare const PlantedParticipants: FC<IconProps>
export declare const PlantedSeed: FC<IconProps>
export declare const PlantSeedSeparated: FC<IconProps>
export declare const Profile: FC<IconProps>
export declare const QrCode: FC<IconProps>
export declare const QrcodeCircle: FC<IconProps>
export declare const QrcodeLeftDiamond: FC<IconProps>
export declare const QrcodeLeftLeaf: FC<IconProps>
export declare const QrcodeRightDiamond: FC<IconProps>
export declare const QrcodeRightLeaf: FC<IconProps>
export declare const QrcodeRounded: FC<IconProps>
export declare const QrcodeSquare: FC<IconProps>
export declare const RectArrowBottom: FC<IconProps>
export declare const ReferFriend: FC<IconProps>
export declare const Restart: FC<IconProps>
export declare const Search: FC<IconProps>
export declare const Seed: FC<IconProps>
export declare const SeedJumping: FC<IconProps>
export declare const SeedLittle: FC<IconProps>
export declare const SeedReward: FC<IconProps>
export declare const SeedSunglasses: FC<IconProps>
export declare const SeedWaving: FC<IconProps>
export declare const SendHome: FC<IconProps>
export declare const SocialAdress: FC<IconProps>
export declare const SocialBehance: FC<IconProps>
export declare const SocialCalendly: FC<IconProps>
export declare const SocialCameo: FC<IconProps>
export declare const SocialCanva: FC<IconProps>
export declare const SocialClubHouse: FC<IconProps>
export declare const SocialDailymotion: FC<IconProps>
export declare const SocialDiscord: FC<IconProps>
export declare const SocialDribble: FC<IconProps>
export declare const SocialEtsy: FC<IconProps>
export declare const SocialFacebook: FC<IconProps>
export declare const SocialGithub: FC<IconProps>
export declare const SocialGmail: FC<IconProps>
export declare const SocialInstagram: FC<IconProps>
export declare const SocialLine: FC<IconProps>
export declare const SocialLinkedin: FC<IconProps>
export declare const SocialMail: FC<IconProps>
export declare const SocialMedium: FC<IconProps>
export declare const SocialMessages: FC<IconProps>
export declare const SocialMsSkype: FC<IconProps>
export declare const SocialMym: FC<IconProps>
export declare const SocialOnlyfans: FC<IconProps>
export declare const SocialOpensea: FC<IconProps>
export declare const SocialPhone: FC<IconProps>
export declare const SocialPinterest: FC<IconProps>
export declare const SocialReddit: FC<IconProps>
export declare const SocialSafari: FC<IconProps>
export declare const SocialSignal: FC<IconProps>
export declare const SocialSnapchat: FC<IconProps>
export declare const SocialSoundcloud: FC<IconProps>
export declare const SocialSpotify: FC<IconProps>
export declare const SocialStrava: FC<IconProps>
export declare const SocialSubstack: FC<IconProps>
export declare const SocialTelegram: FC<IconProps>
export declare const SocialTiktok: FC<IconProps>
export declare const SocialTwitch: FC<IconProps>
export declare const SocialTwitter: FC<IconProps>
export declare const SocialUnsplash: FC<IconProps>
export declare const SocialViber: FC<IconProps>
export declare const SocialVimeo: FC<IconProps>
export declare const SocialWechat: FC<IconProps>
export declare const SocialWhatsapp: FC<IconProps>
export declare const SocialYoutube: FC<IconProps>
export declare const Star: FC<IconProps>
export declare const StarEpic: FC<IconProps>
export declare const Subtract: FC<IconProps>
export declare const Tablet: FC<IconProps>
export declare const Target: FC<IconProps>
export declare const ThreePeopleLinear: FC<IconProps>
export declare const TooltipPointer: FC<IconProps>
export declare const TooltipPointerTop: FC<IconProps>
export declare const Tree: FC<IconProps>
export declare const Trees: FC<IconProps>
export declare const Tripadvisor: FC<IconProps>
export declare const User: FC<IconProps>
export declare const UserScan: FC<IconProps>
export declare const VersionIcon: FC<IconProps>
export declare const Video: FC<IconProps>
export declare const Waterdrop: FC<IconProps>
